// This file is generated by npm run audio:generate. Do not edit by hand.
import type { AudioSource } from 'expo-audio';

export const audioSources: Readonly<Record<string, AudioSource>> = {
  "el-kalimera": require("../../../../assets/audio/el-GR/el-kalimera.mp3"),
  "el-letter-alpha": require("../../../../assets/audio/el-GR/el-letter-alpha.mp3"),
  "el-letter-epsilon": require("../../../../assets/audio/el-GR/el-letter-epsilon.mp3"),
  "el-letter-iota": require("../../../../assets/audio/el-GR/el-letter-iota.mp3"),
  "el-nero": require("../../../../assets/audio/el-GR/el-nero.mp3"),
  "el-vowels-kalimera": require("../../../../assets/audio/el-GR/el-vowels-kalimera.mp3"),
};
